import importlib

importlib.import_module("am.wav", "times")
importlib.import_module("pm.wav", "times")
importlib.import_module("one.wav", "times")
importlib.import_module("two.wav", "times")
importlib.import_module("three.wav", "times")
importlib.import_module("four.wav",2"times")
importlib.import_module("five.wav", "times")
importlib.import_module("six.wav", "times")
importlib.import_module("seven.wav", "times")
importlib.import_module("eight.wav", "times")
importlib.import_module("nine.wav", "times")
importlib.import_module("ten.wav", "times")
importlib.import_module("eleven.wav", "times")
importlib.import_module("twelve.wav","times")
