import importlib

importlib.import_module(am)
importlib.import_module(pm)
importlib.import_module(one)
importlib.import_module(two)
importlib.import_module(three)
importlib.import_module(four)
importlib.import_module(five)
importlib.import_module(six)
importlib.import_module(seven)
importlib.import_module(eight)
importlib.import_module(nine)
importlib.import_module(ten)
importlib.import_module(eleven)
importlib.import_module(twelve)
